baseURL = "https://karanveersp.github.io/"
languageCode = "en-us"
title = "Karanveer"
theme = "ezhil"

copyright = "2019 Karanveer"

# Your Disqus sortname.
disqusShortname = "https-karanveersp-github-io"

[params]
    # blog subtitle. supports markdown
    subtitle = "Code Commander"

    # content types which are included in  home page recent posts list
    mainSections = ["posts"]

    # content types which exclude Disqus comments
    disableDisqusTypes = ["page"]

    mode = "dark"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    #customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`.
    #customJS = ["js/abc.js", "js/xyz.js"]
    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

    [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

    [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

    # Social media links on site header
    # uses feather icons for icons.
    [[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/karanveersp"

    # enable tags
    [taxonomies]
        tag = "tags"